data = {
    "groups": [
        {
            "id": "1",
            "name": "技术中心",
            "code": "JSZX",
            "reviser": "系统管理员",
            "mtime": "2017-06-22 11: 55: 16",
        },
        {
            "id": "2",
            "name": "运营中心",
            "code": "YYZX",
            "reviser": "普通管理员",
            "mtime": "2017-06-22 11: 55: 16",
        },
        {
            "id": "3",
            "name": "财务风控中心",
            "code": "CW",
            "reviser": "系统管理员",
            "mtime": "2017-06-22 11: 55: 16",
        },
        {
            "id": "4",
            "name": "支持中心",
            "code": "ZC",
            "reviser": "普通管理员",
           "mtime": "2017-06-22 11: 55: 16",
        },
    ],

    "members": [
        {
            "group_id": 1,
            "workId": 1,
            "userId": 1,
            "password": "e8a22192-e53d-437b-8e44-6323a73868fd",
            "isActive": false,
            "avatar": "http://placehold.it/32x32",
            "realname": "Parrish Suarez",
            "pic": "http://placehold.it/32x32",
            "sex": "male",
            "nickname": "KNOWLYSIS",
            "email": "parrishsuarez@knowlysis.com",
            "tel": "+1 (883) 454-3306",
            "fax": "+1 (920) 482-3918",
            "area": "835 Gerry Street, Snyderville, Maine, 6302",
            "ps": "Occaecat exercitation aliquip pariatur occaecat eiusmod enim dolore duis occaecat. Pariatur aliquip culpa tempor nulla. Sunt eu laboris do ex in culpa amet voluptate dolor pariatur sit. Tempor ipsum enim nulla excepteur cupidatat velit fugiat do officia ipsum. Culpa id id ad do officia cillum culpa labore minim ex officia. Aliquip minim dolore commodo nostrud qui ad.\r\n",
            "birthday": "2015-11-07T01:27:40 -08:00"
        },
        {
            "group_id": 1,
            "workId": 2,
            "userId": 2,
            "password": "e13e2248-e78e-4214-aba9-d03880097456",
            "isActive": true,
            "avatar": "http://placehold.it/32x32",
            "realname": "Howell David",
            "pic": "http://placehold.it/32x32",
            "sex": "male",
            "nickname": "REALMO",
            "email": "howelldavid@realmo.com",
            "tel": "+1 (987) 408-2868",
            "fax": "+1 (938) 451-2561",
            "area": "987 Strauss Street, Elfrida, South Dakota, 4605",
            "ps": "Do non cupidatat elit id. Do enim culpa ea do dolore fugiat laborum nisi. Irure tempor consectetur laboris dolor enim laboris commodo enim id elit eiusmod. Et laboris ullamco pariatur aliqua culpa mollit occaecat. Pariatur ea laborum deserunt veniam laboris aliqua. Consectetur aliqua reprehenderit adipisicing ullamco. Fugiat duis proident do enim qui mollit quis sit ullamco ex exercitation eiusmod.\r\n",
            "birthday": "2017-08-28T08:17:34 -08:00"
        },
        {
            "group_id": 2,
            "workId": 1,
            "userId": 1,
            "password": "9730ac79-6e82-4f5f-92e6-5f6a4c3b3236",
            "isActive": true,
            "avatar": "http://placehold.it/32x32",
            "realname": "Christian Farley",
            "pic": "http://placehold.it/32x32",
            "sex": "female",
            "nickname": "MAKINGWAY",
            "email": "christianfarley@makingway.com",
            "tel": "+1 (948) 542-2564",
            "fax": "+1 (866) 557-3408",
            "area": "512 Tilden Avenue, Galesville, Missouri, 6705",
            "ps": "Occaecat adipisicing occaecat laboris sunt Lorem enim qui. Aute cillum eiusmod ut nulla ipsum fugiat in minim commodo quis. Est est ullamco irure Lorem veniam sunt tempor aute cupidatat nostrud quis Lorem velit. Consequat mollit eiusmod laboris mollit aliquip aliquip culpa nisi velit eu. Nostrud labore sit ex nulla aliquip officia sint deserunt sunt Lorem excepteur proident irure velit.\r\n",
            "birthday": "2016-04-18T02:15:27 -08:00"
        },
        {
            "group_id": 2,
            "workId": 2,
            "userId": 2,
            "password": "331f2ddd-419a-470d-9af3-009e87107f32",
            "isActive": false,
            "avatar": "http://placehold.it/32x32",
            "realname": "Ava Weeks",
            "pic": "http://placehold.it/32x32",
            "sex": "female",
            "nickname": "OVOLO",
            "email": "avaweeks@ovolo.com",
            "tel": "+1 (800) 452-2528",
            "fax": "+1 (866) 570-2716",
            "area": "154 Varanda Place, Grenelefe, Colorado, 2292",
            "ps": "Sunt elit minim culpa minim officia consectetur ex et fugiat aute eiusmod. Voluptate sit culpa cillum culpa ea laboris amet exercitation minim. Id sint velit occaecat consequat minim est sit nulla est id.\r\n",
            "birthday": "2017-10-05T02:58:13 -08:00"
        },
        {
            "group_id": 3,
            "workId": 1,
            "userId": 1,
            "password": "beb23462-f83b-4560-b6ba-6d76cbd425a5",
            "isActive": false,
            "avatar": "http://placehold.it/32x32",
            "realname": "Margo Wiley",
            "pic": "http://placehold.it/32x32",
            "sex": "female",
            "nickname": "ZILLACOM",
            "email": "margowiley@zillacom.com",
            "tel": "+1 (930) 490-3520",
            "fax": "+1 (875) 436-2894",
            "area": "273 Lake Avenue, Forbestown, Ohio, 3808",
            "ps": "Esse ipsum nostrud fugiat cillum deserunt amet nisi cupidatat voluptate anim do. Esse proident veniam nulla officia officia aliqua. Proident nulla mollit ipsum amet non Lorem mollit esse veniam sit aliquip dolor irure dolor. Enim ut minim id veniam ipsum tempor aliquip nostrud pariatur exercitation occaecat quis consectetur. Tempor in officia velit nisi qui nisi adipisicing cillum esse. Culpa in irure tempor laborum enim aute dolore tempor.\r\n",
            "birthday": "2017-01-10T08:32:43 -08:00"
        }, {
            "group_id": 3,
            "workId": 2,
            "userId": 2,
            "password": "928a0f7e-bdc0-4f01-b6e7-0587abbe091a",
            "isActive": true,
            "avatar": "http://placehold.it/32x32",
            "realname": "Liz Mclean",
            "pic": "http://placehold.it/32x32",
            "sex": "female",
            "nickname": "ASSISTIA",
            "email": "lizmclean@assistia.com",
            "tel": "+1 (962) 424-2861",
            "fax": "+1 (954) 484-3034",
            "area": "663 Fayette Street, Motley, Arkansas, 5787",
            "ps": "Excepteur occaecat sunt proident consequat laborum proident exercitation deserunt. Deserunt commodo consectetur occaecat tempor dolor et anim. Aliquip quis in amet proident exercitation culpa. Labore cupidatat eu aliqua sunt eu exercitation duis culpa eu cillum elit reprehenderit Lorem commodo. Tempor est tempor cillum quis sunt quis id magna laboris.\r\n",
            "birthday": "2016-11-14T03:13:42 -08:00"
        },
        {
            "group_id": 4,
            "workId": 1,
            "userId": 1,
            "password": "9a5c3874-67fe-450d-b55c-3e74b45ca475",
            "isActive": true,
            "avatar": "http://placehold.it/32x32",
            "realname": "Kaye Lopez",
            "pic": "http://placehold.it/32x32",
            "sex": "female",
            "nickname": "ZUVY",
            "email": "kayelopez@zuvy.com",
            "tel": "+1 (876) 481-3776",
            "fax": "+1 (811) 541-3716",
            "area": "534 Franklin Avenue, Norris, Florida, 9865",
            "ps": "Velit sit pariatur nostrud ad sunt elit duis in laborum deserunt in esse culpa pariatur. Consequat mollit adipisicing sit cupidatat labore do consequat. Incididunt ut in tempor ut laboris qui in nulla deserunt tempor pariatur esse laborum. Non commodo Lorem proident ea nisi consequat in ut do sunt. Ipsum esse minim reprehenderit laboris eu tempor nisi ipsum incididunt dolore irure do pariatur. Aute consectetur cillum nisi dolor cupidatat fugiat consequat sint eiusmod occaecat non adipisicing.\r\n",
            "birthday": "2017-10-12T07:36:35 -08:00"
        },
        {
            "group_id": 4,
            "workId": 2,
            "userId": 2,
            "password": "b78748bd-a230-4469-b473-1df82f4b14b6",
            "isActive": false,
            "avatar": "http://placehold.it/32x32",
            "realname": "Landry Irwin",
            "pic": "http://placehold.it/32x32",
            "sex": "male",
            "nickname": "DIGIQUE",
            "email": "landryirwin@digique.com",
            "tel": "+1 (898) 472-2332",
            "fax": "+1 (954) 444-3106",
            "area": "640 Ovington Court, Maplewood, Virginia, 7989",
            "ps": "Ipsum quis commodo esse id do minim. Ullamco ullamco sit ad dolor ad duis aute. Excepteur aute excepteur sit sit. Aliqua nisi officia occaecat magna sit id sint reprehenderit dolore magna pariatur eiusmod. Commodo esse dolor id mollit culpa in dolor aliquip ipsum qui elit.\r\n",
            "birthday": "2015-11-24T04:00:09 -08:00"
        },




    ]



}